use mangen for options handling

diff --git a/DayZAddonBuilder b/DayZAddonBuilder
--- a/DayZAddonBuilder
+++ b/DayZAddonBuilder
@@ -6,6 +6,7 @@ addonBuilderExe=$(xmllint "/home/simonvic/Documents/Productivity/Programming/scr
 args=()
 srcDir=""
 destDir=""
+dryRun=false
 
 ##
 # 0 = no output
@@ -14,147 +15,6 @@ destDir=""
 # 3 = mod list | windows output | arguments | executables
 # 4 = mod list | windows output | arguments | executables | final command 
 verbosity=0
-
-dryRun=false
-
-function printUsage() {
-	printf "
-- Usage
-	DayZAddonBuilder [-hvocbl] [-s sourcePath] [-d destinationPath] [-t tempFolderPath] [-p addonPrefix] [-P projectPath] [-k privateKey] [-K privateKey] [-i filesToInclude] [-e filesToExclude] [-V pboVersion] [-B binarize.exe] [-C cfgConvert.exe] [-F filebank.exe] [-D dssignfile.exe] [-T dayzToolsPath] 
-	
-- Options
-	-h, --help                             Show this help.
-	-v, --verbose                          Be verbose. Can be repeated for more verbosity.
-
-	-o, --only-pack                        Only stores the folder to a PBO. Does NOT binarize 
-	                                        files. (Binarization is default behaviour.)
-
-	-c, --clear-temp                       Before binarizing, the content of subfolder for the 
-	                                        current project is deleted.
-
-	-b, --binarize-all-textures            Binarize all .TGA, .PNG textures even if they are not
-	                                        referenced by any model or included in
-	                                        any textures.lst file.
-
-	-l, --extended-logs                    Enable extended logging	
-
-	-t, --temp <folder>                    Path for the folder which stores binarized files, 
-	                                        default destination is temp in Windows, if no 
-	                                        value is present then the last folder is used, 
-	                                        if you use the same folder, the next time you 
-	                                        binarize the same addon it will take less time.
-
-	-p, --prefix <prefix>                  Relative path to files used in addon, if not present
-	                                        then this value is calculated automatically.
-
-	-P, --project-path <path>              Path to folder where project starts from, if you are 
-	                                        packing only the path of a project. It is recommended
-	                                        to use the same as the source path or to define it
-	                                        accordingly to the need. 
-	                                        In case it is defined to P:, Binarize will process the
-	                                        entire P: drive which takes time.
-
-	-k, --sign-with <key>                  Private BI key (*.BIPRIVATEKEY) file that will be used
-	                                        to sign the addon. Addons created with a signature can 
-	                                        be added to secure servers.
-
-	-K, --sign-with-copy <key>             Private BI key (*.BIPRIVATEKEY) file that will be used
-	                                        to sign the addon. Addons created with a signature can 
-	                                        be added to secure servers.
-											The key will also be copied in the destination directory
-
-	-i, --include <files>                  Directly copy matched files to PBO.
-	                                        Absolute path to file with wildcard patterns.
-	                                        Separator is ';' and ','.
-
-	-e, --exclude <files>                  Absolute or relative file path. Contains patterns of
-	                                        files which are excluded from final pbo. Look for
-	                                        'exclude.lst' file in DayZTools install dir for
-	                                        an example of exclude file content.
-
-	-V, --pbo-version <version>            PBO version for FileBank (-property version=<version>)
-
-	-B, --binarize-exe <exe>               Path to Binarize tool. Default Binarize tool is used
-	                                        if not specified.
-	
-	-C, --cfgConvert-exe <exe>             Path to cfg convert tool. Default is used if not 
-	                                        specified.
-
-	-F, --filebank-exe <exe>               Path to cfg filebank tool. Default is used if not 
-	                                        specified.
-
-	-D, --dssignfile-exe <exe>             Path to cfg DssignFile  tool. Default is used if not 
-	                                        specified.
-
-	-T, --dayz-tools <folder>              Specifies the path to DayZ Tools directory with other 
-	                                        tools (Binarize, CfgConvert, Filebank, ...). By default 
-	                                        is the directory retrieved from Steam client.
-	
-	--dry-run                              Emulate the build without actually doing anything
-
-	
-"
-}
-
-function setupLaunchParameters() {
-	local shortOpt="hvocbls:d:t:p:P:k:K:i:e:V:B:C:F:D:T:"
-	local longOpt="help,verbose,only-pack,clear-temp,binarize-all-textures,extended-logs,source:,destination:,temp-folder:,prefix:,project-path:,sign-with:,sign-with-copy:,include:,exclude:,pbo-version:,binarize-exe:,cfgConvert-exe:,filebank-exe:,dssignfile-exe:,dayz-tools:,dry-run"
-
-	local parsedArgs=$(getopt -n DayZAddonBuilder -o ${shortOpt} --long ${longOpt} -- "$@")
-	if [ "$?" != "0" ]; then
-		printUsage
-		exit 1
-	fi
-
-	eval set -- "$parsedArgs"
-
-	while true; do
-		case $1 in
-		-h | --help)
-			printUsage
-			exit 1
-			;;
-		-v | --verbose)               ((verbosity++))                                  ;;
-		-o | --only-pack)             args+=("-packonly")                              ;;
-		-c | --clear-temp)            args+=("-clear")                                 ;;
-		-b | --binarize-all-textures) args+=("-binarizeAllTextures")                   ;;
-		-l | --extended-logs)         args+=("-binarizeFullLogs")                      ;;
-		-s | --source)                srcDir="$2"                              ; shift ;;
-		-d | --destination)           destDir="$2"                             ; shift ;;
-		-t | --temp-folder)           args+=("-temp=$2")                       ; shift ;;
-		-p | --prefix)                args+=("-prefix=$2")                     ; shift ;;
-		-P | --project-path)          args+=("-project=$2")                    ; shift ;;
-		-k | --sign-with)             privateKey="$2"                          ; shift ;;
-		-K | --sign-with-copy)        privateKey="$2" && willCopyKey=true      ; shift ;;
-		-i | --include)               args+=("-include=$2")                    ; shift ;;
-		-V | --pbo-version)           args+=("-pboversion=$2")                 ; shift ;;
-		-B | --binarize-exe)          args+=("-binarize=$2")                   ; shift ;;
-		-C | --cfgConvert-exe)        args+=("-cfgconvert=$2")                 ; shift ;;
-		-F | --filebank-exe)          args+=("-filebank=$2")                   ; shift ;;
-		-D | --dssignfile-exe)        args+=("-dssignfile=$2")                 ; shift ;;
-		-T | --dayz-tools)            args+=("-toolsDirectory=$2")             ; shift ;;
-		-e | --exclude)
-			echo "WARNING: Exclude command is broken. Ignoring it. Edit the default exclude.lst file to exclude files"
-			# args+=("-exclude=$2"); shift
-			shift
-			;;
-		--dry-run) dryRun=true ;;
-		--)
-			shift
-			break
-			;;
-		*)
-			echo "Invalid option: $1"
-			printUsage
-			exit 1
-			;;
-		esac
-		shift #go to next arg
-	done
-
-	[[ -n "$privateKey" ]] && args+=("-sign=$privateKey")
-}
-
 
 ##
 #	Print information on parameters used when executing the command
@@ -234,9 +94,106 @@ function copyModDescriptor() {
 	fi
 }
 
-#############################################
-# MAIN
-setupLaunchParameters "$@"
+options=(
+	"h,help                    --Print this page and exit"
+	"v,verbose                 --Be verbose. Can be repeated for more verbosity"
+	"s,source:dir              --Source directory to build"
+	"d,destination:dir         --Destination directory of the built mod"
+	"o,only-pack               --Only stores the folder to a PBO. Does NOT binarize files. (Binarization is default behaviour.)"
+	"c,clear-temp              --Before binarizing, the content of subfolder for the current project is deleted."
+	"b,binarize-all-textures   --Binarize all .TGA, .PNG textures even if they are not referenced by any model or included in any textures.lst file."
+	"l,extended-logs           --Enable extended logging"
+	"t,temp-folder:dir         --Path for the directory which stores binarized files, default destination is temp in Windows
+	                                 If no value is present then the last folder is used
+	                                 If you use the same folder, the next time you binarize the same addon it will take less time."
+	"p,prefix:prefix           --Relative path to files used in addon, if not present then this value is calculated automatically."
+	"P,project-path:path       --Path to folder where project starts from, if you are packing only the path of a project.
+	                                 It is recommended to use the same as the source path or to define it accordingly to the need. 
+	                                 In case it is defined to P:, Binarize will process the entire P: drive which takes time."
+	"k,sign-with:key           --Private BI key (*.BIPRIVATEKEY) file that will be used to sign the addon.
+	                                 Addons created with a signature can be added to secure servers."
+	"K,sign-with-copy:key      --Private BI key (*.BIPRIVATEKEY) file that will be used to sign the addon.
+	                                 Addons created with a signature can be added to secure servers.
+	                                 The key will also be copied in the destination directory"
+	"i,include:files           --Directly copy matched files to PBO.
+	                                 Absolute path to file with wildcard patterns.
+	                                 Separator is ';' and ','."
+	"e,exclude:files           --Absolute or relative file path.
+	                                 Contains patterns of files which are excluded from final pbo.
+	                                 Look for 'exclude.lst' file in DayZTools install dir for an example of exclude file content."
+	"V,pbo-version:version     --PBO version for FileBank (-property version=<version>)"
+	"B,binarize-exe:exe        --Path to Binarize tool. Default Binarize tool is used if not specified."
+	"C,cfgConvert-exe:exe      --Path to cfg convert tool. Default is used if not specified."
+	"F,filebank-exe:exe        --Path to cfg filebank tool. Default is used if not specified."
+	"D,dssignfile-exe:exe      --Path to cfg DssignFile  tool. Default is used if not specified."
+	"T,dayz-tools:folder       --Specifies the path to DayZ Tools directory with other tools (Binarize, CfgConvert, Filebank, ...).
+	                                 By default is the directory retrieved from Steam client."
+	"-dry-run                  --Simulate the buildign without actually doing anything"
+)
+_options=$(declare -p options)
+
+function printUsage() {
+	mangen \
+		--name "${0##*/}" \
+		--options "$_options" \
+		--command-width 40 \
+		--description-width 80 \
+		--new-line-indent 4
+}
+
+function parseArgs() {
+	local parsedArgs
+	parsedArgs=$(getopt -n "${0##*/}" -o "$(mangen -so "$_options")" --long "$(mangen -lo "$_options")" -- "$@")
+	[[ "$?" != "0" ]] && exit 1
+	eval set -- "$parsedArgs"
+
+	while true; do
+		case $1 in
+		-h | --help)                  printUsage; exit 1 ;;
+		-v | --verbose)               ((verbosity++))                            ;;
+		-o | --only-pack)             args+=("-packonly")                        ;;
+		-c | --clear-temp)            args+=("-clear")                           ;;
+		-b | --binarize-all-textures) args+=("-binarizeAllTextures")             ;;
+		-l | --extended-logs)         args+=("-binarizeFullLogs")                ;;
+		-s | --source)                srcDir="$2"                        ; shift ;;
+		-d | --destination)           destDir="$2"                       ; shift ;;
+		-t | --temp-folder)           args+=("-temp=$2")                 ; shift ;;
+		-p | --prefix)                args+=("-prefix=$2")               ; shift ;;
+		-P | --project-path)          args+=("-project=$2")              ; shift ;;
+		-k | --sign-with)             privateKey="$2"                    ; shift ;;
+		-K | --sign-with-copy)        privateKey="$2"; willCopyKey=true  ; shift ;;
+		-i | --include)               args+=("-include=$2")              ; shift ;;
+		-V | --pbo-version)           args+=("-pboversion=$2")           ; shift ;;
+		-B | --binarize-exe)          args+=("-binarize=$2")             ; shift ;;
+		-C | --cfgConvert-exe)        args+=("-cfgconvert=$2")           ; shift ;;
+		-F | --filebank-exe)          args+=("-filebank=$2")             ; shift ;;
+		-D | --dssignfile-exe)        args+=("-dssignfile=$2")           ; shift ;;
+		-T | --dayz-tools)            args+=("-toolsDirectory=$2")       ; shift ;;
+		-e | --exclude)
+			echo "WARNING: Exclude command is broken. Ignoring it. Edit the default exclude.lst file to exclude files"
+			# args+=("-exclude=$2"); shift
+			shift
+			;;
+		--dry-run) dryRun=true ;;
+		--)
+			shift
+			break
+			;;
+		*)
+			echo "Invalid option: $1"
+			printUsage
+			exit 1
+			;;
+		esac
+		shift #go to next arg
+	done
+
+	[[ -n "$privateKey" ]] && args+=("-sign=$privateKey")
+}
+
+
+###############################################################################
+parseArgs "$@"
 [[ "$dryRun" == true ]] && printf "%s\n" "> DRY RUN..."
 
 # Launch GUI
diff --git a/DayZServerLauncher b/DayZServerLauncher
--- a/DayZServerLauncher
+++ b/DayZServerLauncher
@@ -18,60 +18,6 @@ args=()
 mods=()
 serverMods=()
 
-function printUsage() {
-	printf "
-- Usage
-	DayZServerLauncher [-hvkdeflanF] [-m modsList] [-s serverMods] [-p portNumber] [-c coresNumber] [-L maxFPS] [-D directory] [-X exeFile] [-C configFile] [-M mission] [-P profileFolder] [-B BEpath]
-	
-- Options
-	-h, --help                        Show this help.
-	-v, --verbose                     Be verbose. Can be repeated for more verbosity
-	-k, --kill                        Kill active processes before starting a new one
-	-e, --experimental                Use experimental executable.
-	-d, --diagnostic                  Use diagnostic executable.
-	-f, --file-patching               Ensures that only PBOs are loaded 
-	                                   and NO unpacked data.
-
-	-l, --do-logs                     Enables all log messages in the server RPT file.
-	-a, --admin-log                   Enables the admin log.
-	-n, --net-log                     Enables the network traffic logging.
-	-F, --freeze-check                Stops the server when frozen for more than 
-	                                   5 min and create a dump file.
-	
-	-m, --mods <mods>                 Loads the specified sub-folders for different mods.
-	                                   Separated by semi-colons. Absolute path and 
-	                                   multiple stacked folders are possible.
-
-	-s, --server-mods <mods>          Loads the specified sub-folders for different
-	                                   server-side (not broadcasted to clients) mods.
-	                                   Separated by semi-colons. Absolute path and 
-	                                   multiple stacked folders are possible.
-
-	-p, --port <port>                 Port to have dedicated server listen on.
-	-c, --cpu-count <cores number>    Sets the number of logical CPU cores to use for
-	                                  parallel tasks processing. It should be less or
-	                                   equal than the numbers of available cores.
-
-	-L, --limit-fps <max fps>         Limits server FPS to specified value (current 
-	                                   max is 200) to lower CPU usage of low population servers.
-
-	-D, --dir <exe directory>         Selects where the executables are found
-	-X, --exe <exe file>              Selects what executable file to be used
-	-C, --config <config>             Selects the Server Config File.
-	-M, --mission <mission>           Selects what mission to use.
-	-P, --profile-folder <profile>    Path to the folder containing server profile. By default, 
-	                                   server logs are written to server profile folder. 
-	                                   Logs/dumps/etc will be created there, along with 
-	                                   BattlEye/BEC/Rcon related files. Windows Environment 
-	                                   variables are supported. E.g. &ampuserprofile&amp
-
-	-B, --battleye-path <path>        Sets a custom path to the Battleye files
-	    --script-define <define>      Specify to load a script preprocessor define.
-	                                   Can be repeated to define more.
-	    --ignore-new-errors           Newly added game / script errors are treated as warning.
-
-"
-}
 
 ##
 #	Kill all Dayz related processes (exe and diagnostic exe)
@@ -99,74 +45,6 @@ function useDiag() {
 function useFilePatching() {
 	useDiag
 	args+=("-filePatching")
-}
-
-function setupLaunchParameters() {
-	local shortOpt="hvkdeflanFm:s:p:c:L:D:X:C:M:P:B:"
-	local longOpt="help,verbose,kill,diagnostic,experimental,file-patching,do-logs,admin-log,net-log,freeze-check,mods:,server-mods:,port:,cpu-count:,limit-fps:,dir:,exe:,config:,mission:,profile-folder:,battleye-path:,script-define:,ignore-new-errors"
-
-	local parsedArgs=$(getopt -n DayZServerLauncher -o ${shortOpt} --long ${longOpt} -- "$@")
-	if [ "$?" != "0" ]; then
-		printUsage
-		exit 1
-	fi
-
-	eval set -- "$parsedArgs"
-
-	while true; do
-		case $1 in
-		-h | --help)
-			printUsage
-			exit 1
-			;;
-		-v | --verbose)        ((verbosity++))                 ;;
-		-k | --kill)           requestedKillProcess=true       ;;
-		-d | --diagnostic)     useDiag                         ;;
-		-e | --experimental)   useExperimental                 ;;
-		-f | --file-patching)  useFilePatching                 ;;
-		-l | --do-logs)        args+=("-doLogs")               ;;
-		-a | --admin-log)      args+=("-adminLog")             ;;
-		-n | --net-log)        args+=("-netLog")               ;;
-		-F | --freeze-check)   args+=("-freezeCheck")          ;;
-		-m | --mods)           mods+=("$2")            ; shift ;;
-		-s | --server-mods)    serverMods+=("$2")      ; shift ;;
-		-p | --port)           args+=("-port=$2")      ; shift ;;
-		-c | --cpu-count)      args+=("-cpuCount=$2")  ; shift ;;
-		-L | --limit-fps)      args+=("-limitFPS=$2")  ; shift ;;
-		-D | --dir)            dir="$2"                ; shift ;;
-		-X | --exe)            exe="$2"                ; shift ;;
-		-C | --config)         args+=("-config=$2")    ; shift ;;
-		-M | --mission)        args+=("-mission=$2")   ; shift ;;
-		-P | --profile-folder) args+=("-profiles=$2")  ; shift ;;
-		-B | --battleye-path)  args+=("-BEpath=$2")    ; shift ;;
-		--script-define)       args+=("-scrDef=$2")    ; shift ;;
-		--ignore-new-errors)   args+=("-newErrorsAreWarnings=1");;
-
-		--)
-			shift
-			break
-			;;
-		*)
-			echo "Invalid option: $1"
-			printUsage
-			exit 1
-			;;
-		esac
-		shift #go to next arg
-	done
-
-	local modsArg=""
-	for mod in "${mods[@]}"; do
-		[[ -z "$modsArg" ]] && modsArg="-mod=$mod" || modsArg="$modsArg;$mod"
-	done
-	[[ -n "$modsArg" ]] && args+=("$modsArg")
-
-	local serverModsArg=""
-	for mod in "${serverMods[@]}"; do
-		[[ -z "$serverModsArg" ]] && serverModsArg="-serverMod=$mod" || serverModsArg="$serverModsArg;$mod"
-	done
-	[[ -n "$serverModsArg" ]] && args+=("$serverModsArg")
-
 }
 
 ##
@@ -220,9 +98,99 @@ function setupExecutables() {
 		fi
 	fi
 }
-#############################################
-# MAIN
-setupLaunchParameters "$@"
+
+options=(
+	"h,help                        --Print this page and exit"
+	"v,verbose                     --Be verbose. Can be repeated for more verbosity"
+	"k,kill                        --Kill active processes before starting a new one"
+	"e,experimental                --Use experimental executable."
+	"d,diagnostic                  --Use diagnostic executable."
+	"f,file-patching               --Ensures that only PBOs are loaded and NO unpacked data."
+	"l,do-logs                     --Enables all log messages in the server RPT file."
+	"a,admin-log                   --Enables the admin log."
+	"n,net-log                     --Enables the network traffic logging."
+	"F,freeze-check                --Stops the server when frozen for more than 5 min and create a dump file."
+	"m,mods:mods                   --Loads the specified sub-folders for different mods.
+	                                   Separated by semi-colons.
+	                                   Absolute path and multiple stacked folders are possible."
+	"s,server-mods:mods            --Loads the specified sub-folders for different server-side (not broadcasted to clients) mods.
+	                                   Separated by semi-colons.
+	                                   Absolute path and multiple stacked folders are possible."
+	"p,port:port                   --Port to have dedicated server listen on."
+	"c,cpu-count:cores-number      --Sets the number of logical CPU cores to use for parallel tasks processing.
+	                                   It should be less or equal than the numbers of available cores."
+	"L,limit-fps:max-fps           --Limits server FPS to specified value (current max is 200) to lower CPU usage of low population servers."
+	"D,dir:exe-directory           --Selects where the executables are found"
+	"X,exe:exe-file                --Selects what executable file to be used"
+	"C,config:config               --Selects the Server Config File."
+	"M,mission:mission             --Selects what mission to use."
+	"P,profile-folder:profile      --Path to the folder containing server profile.
+	                                   By default, server logs are written to server profile folder. 
+	                                   Logs/dumps/etc will be created there, along with BattlEye/BEC/Rcon related files.
+	                                   Windows Environment variables are supported. E.g. &ampuserprofile&amp"
+	"B,battleye-path:path         --Sets a custom path to the Battleye files"
+	"script-define:define         --Specify to load a script preprocessor define.
+	                                   Can be repeated to define more."
+	"ignore-new-errors            --Newly added game / script errors are treated as warning."
+)
+_options=$(declare -p options)
+
+function printUsage() {
+	mangen \
+		--name "${0##*/}" \
+		--options "$_options" \
+		--command-width 35 \
+		--description-width 80 \
+		--new-line-indent 4
+}
+
+function parseArgs() {
+	local parsedArgs
+	parsedArgs=$(getopt -n "${0##*/}" -o "$(mangen -so "$_options")" --long "$(mangen -lo "$_options")" -- "$@")
+	[[ "$?" != "0" ]] && exit 1
+	eval set -- "$parsedArgs"
+
+	while true; do
+		case $1 in
+			-h | --help)           printUsage; exit 1 ;;
+			-v | --verbose)        ((verbosity++))                   ;;
+			-k | --kill)           requestedKillProcess=true         ;;
+			-d | --diagnostic)     useDiag                           ;;
+			-e | --experimental)   useExperimental                   ;;
+			-f | --file-patching)  useFilePatching                   ;;
+			-l | --do-logs)        args+=("-doLogs")                 ;;
+			-a | --admin-log)      args+=("-adminLog")               ;;
+			-n | --net-log)        args+=("-netLog")                 ;;
+			-F | --freeze-check)   args+=("-freezeCheck")            ;;
+			-m | --mods)           mods+=("$2")              ; shift ;;
+			-s | --server-mods)    serverMods+=("$2")        ; shift ;;
+			-p | --port)           args+=("-port=$2")        ; shift ;;
+			-c | --cpu-count)      args+=("-cpuCount=$2")    ; shift ;;
+			-L | --limit-fps)      args+=("-limitFPS=$2")    ; shift ;;
+			-D | --dir)            dir="$2"                  ; shift ;;
+			-X | --exe)            exe="$2"                  ; shift ;;
+			-C | --config)         args+=("-config=$2")      ; shift ;;
+			-M | --mission)        args+=("-mission=$2")     ; shift ;;
+			-P | --profile-folder) args+=("-profiles=$2")    ; shift ;;
+			-B | --battleye-path)  args+=("-BEpath=$2")      ; shift ;;
+			--script-define)       args+=("-scrDef=$2")      ; shift ;;
+			--ignore-new-errors)   args+=("-newErrorsAreWarnings=1") ;;
+
+			--)
+				shift
+				break
+				;;
+			*)
+				echo "Invalid option: $1"
+				exit 1
+				;;
+			esac
+		shift #go to next arg
+	done
+}
+
+###############################################################################
+parseArgs "$@"
 setupExecutables
 [[ $requestedKillProcess == true ]] && killAllProcesses
 [[ $verbosity -ge 1 ]] && printLaunchParameters
diff --git a/DayZWorkbenchLauncher b/DayZWorkbenchLauncher
--- a/DayZWorkbenchLauncher
+++ b/DayZWorkbenchLauncher
@@ -3,80 +3,68 @@
 source DayZLauncherUtil
 
 workbenchExe=$(queryCfg "/config/tools/workbench/text()")
-mods=""
+mods=()
 
 verbosity=0
 
-function printUsage() {
-	printf "
-- Usage
-	DayZWorkbenchLauncher [-hv] [-m modsList] [-X exeFile]
-	
-- Options
-	-h, --help                     Show this help.
-	-v, --verbose                  Be verbose. Can be repeated for more verbosity
-	-m, --mods <mods>              Loads the specified sub-folders for different mods.
-	                                Separated by semi-colons. Absolute path and 
-	                                multiple stacked folders are possible.
-
-	-X, --exe <exe path>           Selects what executable file to be used
-	    --script-define <define>   Specify to load a script preprocessor define.
-	                                Can be repeated to define more.
-"
+##
+# @return formatted mod arg (i.e. --mods=A;B;C;D)
+function getFormattedModsArgs() {
+	local modsArg=""
+	for mod in "${mods[@]}"; do
+		[[ -z "$modsArg" ]] && modsArg="-mod=$mod" || modsArg="$modsArg;$mod"
+	done
+	printf "%s" "$modsArg"
 }
 
-function setupLaunchParameters() {
-	local shortOpt="hvm:X:"
-	local longOpt="help,verbose,mods:,exe:,script-define:"
+options=(
+	"h,help                --Print this page and exit"
+	"v,verbose             --Be verbose. Can be repeated for more verbosity"
+	"m,mods:mods           --Loads the specified sub-folders for different mods.
+	                           Separated by semi-colons.
+	                           Absolute path and multiple stacked folders are possible. "
+	"X,exe:exe-path        --Select what executable file to use"
+	"script-define:define  --Specify to load a script preprocessor define.
+	                           Can be repeated to define more"
+)
+_options=$(declare -p options)
 
-	local parsedArgs=$(getopt -n DayZWorkbenchLauncher -o ${shortOpt} --long ${longOpt} -- "$@")
-	if [ "$?" != "0" ]; then
-		printUsage
-		exit 1
-	fi
+function printUsage() {
+	mangen \
+		--name "${0##*/}" \
+		--options "$_options" \
+		--command-width 35 \
+		--description-width 80 \
+		--new-line-indent 4
+}
 
+function parseArgs() {
+	local parsedArgs
+	parsedArgs=$(getopt -n "${0##*/}" -o "$(mangen -so "$_options")" --long "$(mangen -lo "$_options")" -- "$@")
+	[[ "$?" != "0" ]] && exit 1
 	eval set -- "$parsedArgs"
 
 	while true; do
 		case $1 in
-		-h | --help) printUsage; exit 1 ;;
-		-v | --verbose) ((verbosity + 1)) ;;
-		-m | --mods) addMod "$2"; shift ;;
-		-X | --exe) setWorkbenchExe "$2"; shift ;;
-		--)
-			shift
-			break
-			;;
-		*)
-			echo "Invalid option: $1"
-			printUsage
-			exit 1
-			;;
-		esac
+			-h | --help) printUsage; exit 1 ;;
+			-v | --verbose) ((verbosity++)) ;;
+			-m | --mods) mods+=("$2"); shift ;;
+			-X | --exe) workbenchExe="$2"; shift ;;
+			--)
+				shift
+				break
+				;;
+			*)
+				echo "Invalid option: $1"
+				exit 1
+				;;
+			esac
 		shift #go to next arg
 	done
-
-	[[ -n $mods ]] && argMods="-mod=$mods"
-
 }
+###############################################################################
 
-function setWorkbenchExe() {
-	if [ -n "$1" ]; then
-		workbenchExe="$1"
-	fi
-}
+parseArgs "$@"
 
-function addMod() {
-	if [ -n "$1" ]; then
-		if [ -n "$mods" ]; then
-			mods="$mods;$1"
-		else
-			mods="$1"
-		fi
-	fi
-}
-
-setupLaunchParameters "$@"
-
-[[ $verbosity -ge 2 ]] && echo "cmd.exe" "/c" "START" "/D" "${workbenchExe%\\*}" ".\\${workbenchExe##*\\}" "$argMods"
-cmd.exe /c "START" "/D" "${workbenchExe%\\*}" ".\\${workbenchExe##*\\}" "$argMods"
+[[ $verbosity -ge 2 ]] && echo "cmd.exe" "/c" "START" "/D" "${workbenchExe%\\*}" ".\\${workbenchExe##*\\}" "$(getFormattedModsArgs)"
+cmd.exe /c "START" "/D" "${workbenchExe%\\*}" ".\\${workbenchExe##*\\}" "$(getFormattedModsArgs)"
diff --git a/cliz b/cliz
--- a/cliz
+++ b/cliz
@@ -8,7 +8,6 @@ serverMission=$(queryCfg '/config/server/defaults/mission/text()')
 serverConfig=$(queryCfg '/config/server/defaults/config/text()')
 serverProfileFolder=$(queryCfg '/config/server/defaults/profile/text()')
 privateKey=$(queryCfg '/config/private-key/text()')
-workshopDir=$(queryCfg '/config/workshop/dir/text()')
 
 verbosity=0
 verbosityArgs=()
@@ -25,12 +24,13 @@ modsToLaunchServerSideResolved=()  # array of paths
 ##
 # @param mod id
 function addModToBuild() {
-	local mod=$(queryCfg "//*[@id='$1']")
-	local modType=$(queryCfg "name(/*)" "$mod")
+	local mod modType deps
+	mod=$(queryCfg "//*[@id='$1']")
+	modType=$(queryCfg "name(/*)" "$mod")
 	case "$modType" in
 		workshop) : ;;
 		group)
-			local deps=$(queryCfgAttr "//deps/dep/@ref" "$mod")
+			deps=$(queryCfgAttr "//deps/dep/@ref" "$mod")
 			if [[ -n "$deps" ]]; then
 				while read -r dep; do
 					addModToBuild "$dep"
@@ -44,13 +44,14 @@ function addModToBuild() {
 ##
 # @param mod id
 function addModToLaunch() {
-	local mod=$(queryCfg "//*[@id='$1']")
-	local modType=$(queryCfg "name(/*)" "$mod")
+	local mod modType deps
+	mod=$(queryCfg "//*[@id='$1']")
+	modType=$(queryCfg "name(/*)" "$mod")
 	case "$modType" in
 		group) : ;;
 		workshop | mod) modsToLaunch+=("$1") ;;
 	esac
-	local deps=$(queryCfgAttr "//deps/dep/@ref" "$mod")
+	deps=$(queryCfgAttr "//deps/dep/@ref" "$mod")
 	if [[ -n "$deps" ]]; then
 		while read -r dep; do
 			addModToLaunch "$dep"
@@ -61,13 +62,14 @@ function addModToLaunch() {
 ##
 # @param mod id
 function addModToLaunchServerSide() {
-	local mod=$(queryCfg "//*[@id='$1']")
-	local modType=$(queryCfg "name(/*)" "$mod")
+	local mod modType deps
+	mod=$(queryCfg "//*[@id='$1']")
+	modType=$(queryCfg "name(/*)" "$mod")
 	case "$modType" in
 		group) : ;;
 		workshop | mod) modsToLaunchServerSide+=("$1") ;;
 	esac
-	local deps=$(queryCfgAttr "//deps/dep/@ref" "$mod")
+	deps=$(queryCfgAttr "//deps/dep/@ref" "$mod")
 	if [[ -n "$deps" ]]; then
 		while read -r dep; do
 			addModToLaunchServerSide "$dep"
@@ -85,6 +87,7 @@ function getFormattedModsArgs() {
 	printf "%s" "$modsArg"
 }
 
+##
 # @return formatted mod arg (i.e. --server-mods=A;B;C;D)
 function getFormattedServerModsArgs() {
 	local modsArg=""
@@ -94,132 +97,10 @@ function getFormattedServerModsArgs() {
 	printf "%s" "$modsArg"
 }
 
-##
-# Launch the server
-function launchServer() {
-	DayZServerLauncher \
-		"${verbosityArgs[@]}" \
-		--do-logs \
-		--admin-log \
-		--net-log \
-		--freeze-check \
-		"${args[@]}" \
-		"${serverArgs[@]}" \
-		"$(getFormattedModsArgs)" \
-		"$(getFormattedServerModsArgs)" \
-		${serverMission:+--mission "$serverMission"} \
-		${serverConfig:+--config "$serverConfig"} \
-		${serverProfileFolder:+--profile-folder "$serverProfileFolder"}
-
-		if [[ ! "$serverMission" =~ "dayzOffline.chernarusplus" ]]; then
-			printf "%s\n" "Using custom mission. Remember to edit your server config ( $serverConfig )!"
-		fi
-}
-
-##
-# Launch the client
-function launchClient() {
-	DayZClientLauncher \
-		"${verbosityArgs[@]}" \
-		--do-logs \
-		--script-debug \
-		--no-pause \
-		"${args[@]}" \
-		"${clientArgs[@]}" \
-		"$(getFormattedModsArgs)" \
-		${serverAddress:+--server-address "$serverAddress"} \
-		${profileName:+--name "$profileName"}
-}
-
-##
-# Build specified mods
-function buildMods() {
-	for source in "${!modsToBuildResolved[@]}"; do
-		DayZAddonBuilder \
-			--verbose \
-			"${verbosityArgs[@]}" \
-			--binarize-all-textures \
-			--extended-logs \
-			--clear-temp \
-			--source "$source" \
-			--destination "${modsToBuildResolved[$source]}" \
-			--prefix "${source/P:\\/}" \
-			--project-path "$source" \
-			${privateKey:+--sign-with-copy "$privateKey"} \
-			--include "P:\ADDON_BUILDER_DATA\toInclude.txt" \
-			--temp-folder "%TEMP%\dayzaddonbuilder"
-	done
-}
-
-OPTIONS=(
-	"h,help                       --Print this page and exit"
-	"v,verbose                    --Be verbose. Can be repeated for more verbosity"
-	"s,launch-server              --Launch the server"
-	"c,launch-client              --Launch the client"
-	"k,kill                       --Kill all game instances"
-	"b,build:mod                  --Specify mod to build. Can be repeated to build multiple mods"
-	"l,launch-mod:mod             --Specify mod to be loaded when launching game client/server"
-	"L,launch-mod-server:mod      --Specify mod to be loaded server side when launching game server"
-	"B,build-and-launch:mod       --Specify mod to build and to be loaded when launching game client/server"
-	"d,diagnostic                 --Use diagnostic executable"
-	"f,file-patching              --Enable file patching. Diagnostic exe will be used."
-	"e,experimental               --Use experimental version of the game client/server"
-	"script-define:define         --Pass a script define. Can be repeated for more"
-	"ignore-new-errors            --New errors are treated as warnings."
-)
-_OPTIONS=$(declare -p OPTIONS)
-
-function printUsage() {
-	mangen \
-		--name "${0##*/}" \
-		--options "$_OPTIONS" \
-		--command-width 35 \
-		--description-width 100 \
-		--new-line-indent 4
-}
-
-function parseArgs() {
-	local parsedArgs=$(getopt -n "${0##*/}" -o "$(mangen -so "$_OPTIONS")" --long "$(mangen -lo "$_OPTIONS")" -- "$@")
-	if [ "$?" != "0" ]; then
-		printUsage
-		exit 1
-	fi
-
-	eval set -- "$parsedArgs"
-
-	while true; do
-		case $1 in
-			-h | --help) printUsage; exit 1 ;;
-			-v | --verbose) ((verbosity++)); verbosityArgs+=("--verbose") ;;
-			-s | --launch-server) willLaunchServer=true ;;
-			-c | --launch-client) willLaunchClient=true ;;
-			-k | --kill-game) willKillGame=true ;;
-			-b | --build) addModToBuild "$2"; shift ;;
-			-l | --launch-mod) addModToLaunch "$2"; shift ;;
-			-L | --launch-mod-server) addModToLaunchServerSide "$2"; shift ;;
-			-B | --build-and-launch) addModToBuild "$2"; addModToLaunch "$2"; shift ;;
-			-f | --file-patching) args+=("--file-patching") ;;
-			-d | --diagnostic) args+=("--diagnostic") ;;
-			-e | --experimental) args+=("--experimental") ;;
-			--ignore-new-errors) args+=("--ignore-new-errors") ;;
-			--script-define) args+=("--script-define=$2"); shift ;;
-			--)
-				shift
-				break
-				;;
-			*)
-				echo "Invalid option: $1"
-				exit 1
-				;;
-			esac
-		shift #go to next arg
-	done
-
-}
-
 function debugConfigMod() {
-	local mod=$(queryCfg "//*[@id='$1']")
-	local deps=$(queryCfgAttr "//*[@id='$1']/deps/dep/@ref")
+	local mod deps
+	mod=$(queryCfg "//*[@id='$1']")
+	deps=$(queryCfgAttr "//*[@id='$1']/deps/dep/@ref")
 	local depsDepth=${2:-0}
 	for i in $(seq "$depsDepth"); do
 		printf "\t"
@@ -293,21 +174,12 @@ function debugResolvedMods() {
 	fi
 }
 
-
-function resolveModDir() {
-	local mod=$(queryCfg "//*[@id='$id']")
-	case "$(queryCfg "name(/*)" "$mod")" in
-		mod) queryCfgAttr "string(//@dir)" "$mod" ;;
-		workshop) queryCfgAttr "concat('$workshopDir\\', string(//@dir))" "$mod" ;;
-		*) : ;;
-	esac
-}
-
+##
+# Resolve IDs of mods to build and launch
 function resolveMods() {
 	for id in "${modsToBuild[@]}"; do
-		local mod=$(queryCfg "//*[@id='$id']")
-		local src
-		local dst
+		local mod src dst
+		mod=$(resolveMod "$id")
 		case "$(queryCfg "name(/*)" "$mod")" in
 			mod)
 				src=$(queryCfgAttr "string(//@source)" "$mod")
@@ -340,11 +212,133 @@ function resolveMods() {
 ##
 # Kill all clients and servers (diag included)
 function killAllProcesses() {
+	printf "%s\n" "> KILLING PROCESSES"
 	killClient "$verbosity"
 	killClientDiag "$verbosity"
 	killServer "$verbosity"
 	killServerDiag "$verbosity"
 }
+
+##
+# Launch the server
+function launchServer() {
+	DayZServerLauncher \
+		"${verbosityArgs[@]}" \
+		--do-logs \
+		--admin-log \
+		--net-log \
+		--freeze-check \
+		"${args[@]}" \
+		"${serverArgs[@]}" \
+		"$(getFormattedModsArgs)" \
+		"$(getFormattedServerModsArgs)" \
+		${serverMission:+--mission "$serverMission"} \
+		${serverConfig:+--config "$serverConfig"} \
+		${serverProfileFolder:+--profile-folder "$serverProfileFolder"}
+
+		if [[ ! "$serverMission" =~ "dayzOffline.chernarusplus" ]]; then
+			printf "%s\n" "Using custom mission. Remember to edit your server config ( $serverConfig )!"
+		fi
+}
+
+##
+# Launch the client
+function launchClient() {
+	DayZClientLauncher \
+		"${verbosityArgs[@]}" \
+		--do-logs \
+		--script-debug \
+		--no-pause \
+		"${args[@]}" \
+		"${clientArgs[@]}" \
+		"$(getFormattedModsArgs)" \
+		${serverAddress:+--server-address "$serverAddress"} \
+		${profileName:+--name "$profileName"}
+}
+
+##
+# Build specified mods
+function buildMods() {
+	for source in "${!modsToBuildResolved[@]}"; do
+		DayZAddonBuilder \
+			--verbose \
+			"${verbosityArgs[@]}" \
+			--binarize-all-textures \
+			--extended-logs \
+			--clear-temp \
+			--source "$source" \
+			--destination "${modsToBuildResolved[$source]}" \
+			--prefix "${source/P:\\/}" \
+			--project-path "$source" \
+			${privateKey:+--sign-with-copy "$privateKey"} \
+			--include "P:\ADDON_BUILDER_DATA\toInclude.txt" \
+			--temp-folder "%TEMP%\dayzaddonbuilder"
+	done
+}
+
+options=(
+	"h,help                       --Print this page and exit"
+	"v,verbose                    --Be verbose. Can be repeated for more verbosity"
+	"s,launch-server              --Launch the server"
+	"c,launch-client              --Launch the client"
+	"k,kill                       --Kill all game instances"
+	"b,build:mod                  --Specify mod to build. Can be repeated to build multiple mods"
+	"l,launch-mod:mod             --Specify mod to be loaded when launching game client/server"
+	"L,launch-mod-server:mod      --Specify mod to be loaded server side when launching game server"
+	"B,build-and-launch:mod       --Specify mod to build and to be loaded when launching game client/server"
+	"d,diagnostic                 --Use diagnostic executable"
+	"f,file-patching              --Enable file patching. Diagnostic exe will be used."
+	"e,experimental               --Use experimental version of the game client/server"
+	"script-define:define         --Pass a script define. Can be repeated for more"
+	"ignore-new-errors            --New errors are treated as warnings."
+)
+_options=$(declare -p options)
+
+function printUsage() {
+	mangen \
+		--name "${0##*/}" \
+		--options "$_options" \
+		--command-width 35 \
+		--description-width 80 \
+		--new-line-indent 4
+}
+
+function parseArgs() {
+	local parsedArgs
+	parsedArgs=$(getopt -n "${0##*/}" -o "$(mangen -so "$_options")" --long "$(mangen -lo "$_options")" -- "$@")
+	[[ "$?" != "0" ]] && exit 1
+	eval set -- "$parsedArgs"
+
+	while true; do
+		case $1 in
+			-h | --help)              printUsage; exit 1 ;;
+			-v | --verbose)           ((verbosity++)); verbosityArgs+=("--verbose") ;;
+			-s | --launch-server)     willLaunchServer=true ;;
+			-c | --launch-client)     willLaunchClient=true ;;
+			-k | --kill-game)         willKillGame=true ;;
+			-b | --build)             addModToBuild "$2"; shift ;;
+			-l | --launch-mod)        addModToLaunch "$2"; shift ;;
+			-L | --launch-mod-server) addModToLaunchServerSide "$2"; shift ;;
+			-B | --build-and-launch)  addModToBuild "$2"; addModToLaunch "$2"; shift ;;
+			-f | --file-patching)     args+=("--file-patching") ;;
+			-d | --diagnostic)        args+=("--diagnostic") ;;
+			-e | --experimental)      args+=("--experimental") ;;
+			--ignore-new-errors)      args+=("--ignore-new-errors") ;;
+			--script-define)          args+=("--script-define=$2"); shift ;;
+			--)
+				shift
+				break
+				;;
+			*)
+				echo "Invalid option: $1"
+				exit 1
+				;;
+			esac
+		shift #go to next arg
+	done
+
+}
+
 
 ##############################################################
 ## MAIN
